"""Offline LLM provider and versioned RoCo role contracts."""

from roco_ebbo.llm.mkp_mock import MKP_MOCK_PROVIDER_VERSION, MKPMockLLMProvider
from roco_ebbo.llm.openai_compatible import (
    AUDIT_SCHEMA_VERSION,
    CONTEXT_AUDIT_SCHEMA_VERSION,
    EOH_PROMPT_VERSION,
    PROVIDER_NAME,
    REQUEST_CONTRACT_VERSION,
    ChatMessage,
    ContextAudit,
    OpenAICompatibleConfig,
    OpenAICompatibleProvider,
    OpenAICompatibleProviderError,
    OpenAICompatibleRequest,
    OpenAICompatibleResponse,
    OpenAICompatibleTransport,
    OpenAITransportError,
    PricingTable,
    ProviderCallAudit,
    ProviderErrorCode,
    TokenCounter,
    TokenUsage,
    TransportErrorKind,
)
from roco_ebbo.llm.prompts import (
    PROMPT_VERSION,
    ROLE_PROMPTS,
    ROLE_TEMPERATURES,
    RoCoRole,
    prompt_for,
)
from roco_ebbo.llm.provider import (
    GeneratedHeuristic,
    LLMProvider,
    MemoryLLMProvider,
    MemoryMutationRequest,
    MemorySummaryRequest,
    MemorySummaryResponse,
    MockLLMProvider,
    RoleLLMProvider,
    RoleRequest,
    RoleResponse,
)

__all__ = [
    "AUDIT_SCHEMA_VERSION",
    "CONTEXT_AUDIT_SCHEMA_VERSION",
    "EOH_PROMPT_VERSION",
    "PROMPT_VERSION",
    "PROVIDER_NAME",
    "REQUEST_CONTRACT_VERSION",
    "ROLE_PROMPTS",
    "ROLE_TEMPERATURES",
    "ChatMessage",
    "ContextAudit",
    "GeneratedHeuristic",
    "LLMProvider",
    "MemoryLLMProvider",
    "MemoryMutationRequest",
    "MemorySummaryRequest",
    "MemorySummaryResponse",
    "MKP_MOCK_PROVIDER_VERSION",
    "MKPMockLLMProvider",
    "MockLLMProvider",
    "OpenAICompatibleConfig",
    "OpenAICompatibleProvider",
    "OpenAICompatibleProviderError",
    "OpenAICompatibleRequest",
    "OpenAICompatibleResponse",
    "OpenAICompatibleTransport",
    "OpenAITransportError",
    "PricingTable",
    "ProviderCallAudit",
    "ProviderErrorCode",
    "RoCoRole",
    "RoleLLMProvider",
    "RoleRequest",
    "RoleResponse",
    "TokenCounter",
    "TokenUsage",
    "TransportErrorKind",
    "prompt_for",
]
